version: '3'
services:
  hugo:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ".:/src"
    entrypoint: bash
    ports:
      - "1313:1313"
    tty: true
    working_dir: /src
