[build]
publish = "info-geo/public"
command = "bundle && hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.101.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
RUBY_VERSION = "3.0.2"
